pipeline {
    agent any
    
    parameters {
        choice(name: 'NUMBER',
            choices: [10,20,30,40,50,60,70,80,90],
            description: 'Select the value for F(n) for the Fibonnai sequence.')
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
        timestamps()
    }
    environment {
       CWD = "${env.WORKSPACE}/Ch03/03_03-run-scripts-from-the-pipeline"
    }
    triggers {
        cron '@midnight'
    }
    stages {
                        dir("${env.WORKSPACE}/Ch03/03_03-run-scripts-from-the-pipeline"){

        stage('Make executable') {
       //         agent {
  //   label 'podman-cloud'
   // label 'docker-jnlp||docker-bibi-slave'
   // }
            steps {
                    sh '''
                    mkdir scripts && cp ./fibonacci.sh scripts/
                    '''
 //               sh('chmod +x /scripts/fibonacci.sh')
                echo "cwd = $CWD"
                sh 'printenv'
                               sh('chmod +x ./scripts/fibonacci.sh')
                
            }
        }
        stage('Relative path') {
            steps {
                sh("./scripts/fibonacci.sh ${env.NUMBER}")
            }
        }
        stage('Full path') {
            steps {
                sh("${env.WORKSPACE}/scripts/fibonacci.sh ${env.NUMBER}")
            }
        }
        stage('Change directory') {
            steps {
                dir("${env.WORKSPACE}/scripts"){
                    sh("./fibonacci.sh ${env.NUMBER}")
                }
            }
        }
    }
    } // dir
}
