pipeline {
 //   agent any
      agent {
  //   label 'podman-cloud'
          label 'docker-jnlp||docker-bibi-slave'
    } 
    parameters {
        choice(name: 'NUMBER',
            choices: [10,20,30,40,50,60,70,80,90],
            description: 'Select the value for F(n) for the Fibonnai sequence.')
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
        timestamps()
    }
    environment {
       CWD = "${env.WORKSPACE}/Ch03/03_03-run-scripts-from-the-pipeline"
    }
    triggers {
        cron '@midnight'
    }
    stages {
      stage ('checkout to agent'){
        steps {
               git branch: "main", 
               url: "https://github.com/vbronfman/essential-jenkins-2468076.git"
         }
        }
        stage('Make executable') {

            steps {
                   dir("${env.WORKSPACE}/Ch03/03_03-run-scripts-from-the-pipeline"){
                   sh '''
                    if [[ ! -d ./scripts ]];then 
                    mkdir scripts 
                    fi
                 cp ./fibonacci.sh scripts/
                    '''
 //               sh('chmod +x /scripts/fibonacci.sh')
                echo "cwd = $CWD"
                sh 'printenv'
                               sh('chmod +x ./scripts/fibonacci.sh')
                
            }// dir
                } 
        }
        stage('Relative path') {
            steps {
                dir("${env.WORKSPACE}/Ch03/03_03-run-scripts-from-the-pipeline"){
                sh("./scripts/fibonacci.sh ${env.NUMBER}")
                } // dir
            }
        }
        stage('Full path') {
            steps {
                dir("${env.WORKSPACE}/Ch03/03_03-run-scripts-from-the-pipeline"){
                sh("${env.WORKSPACE}/scripts/fibonacci.sh ${env.NUMBER}")
                } // dir
            }
        }
        stage('Change directory') {
            steps {
                dir("${env.WORKSPACE}/Ch03/03_03-run-scripts-from-the-pipeline/scripts"){
                    sh("./fibonacci.sh ${env.NUMBER}")
                }
            }
        }
    }
    
}
